# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x06sensor\"!\n\x11SensorDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"%\n\x12SensorDataResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2[\n\rSensorService\x12J\n\x11ProcessSensorData\x12\x19.sensor.SensorDataRequest\x1a\x1a.sensor.SensorDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATAREQUEST']._serialized_start=24
  _globals['_SENSORDATAREQUEST']._serialized_end=57
  _globals['_SENSORDATARESPONSE']._serialized_start=59
  _globals['_SENSORDATARESPONSE']._serialized_end=96
  _globals['_SENSORSERVICE']._serialized_start=98
  _globals['_SENSORSERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
