version: '3'
services:
  sensor:
    build: ./sensor
    depends_on:
      - gateway
  gateway:
    build: ./gateway
    ports:
      - "65432:65432"
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  microservice:
    build: ./microservice
    depends_on:
      rabbitmq:
        condition: service_healthy
  dashboard:
    build: ./dashboard
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy